#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Updated /etc/hosts:"
echo "localhost now resolves to 127.0.0.2"
echo "facebook.com now resolves to 8.8.8.8"
